// export const VideoContent = [
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
//   {
//     videoTitle: "I'm YouTuber",
//     videoCreator: "I'm Creator",
//     videoClick: "1.5M views",
//     videoTime: "2 days ago",
//   },
// ];

// export default VideoContent;
